// Sample hard-coded business list
const businessList = [
	{
		name: "Margaret",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "9 Ebsworth Rd Rose Bay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2029,
		category: "Italian",
		rating: 5.0,
		review_count: 50,
	},
	{
		name: "Oborozouki",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "5 Quay Street Circular Quay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2000,
		category: "Japanese",
		rating: 4.5,
		review_count: 100,
	},
	{
		name: "Rose bay hotel",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "5 Quay Street Circular Quay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2000,
		category: "Japanese",
		rating: 4.5,
		review_count: 100,
	},
	{
		name: "Chick fila",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "5 Quay Street Circular Quay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2000,
		category: "Japanese",
		rating: 4.5,
		review_count: 100,
	},
	{
		name: "Taco tuesday",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "5 Quay Street Circular Quay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2000,
		category: "Japanese",
		rating: 4.5,
		review_count: 100,
	},
	{
		name: "Lebron james",
		image: "https://www.theworlds50best.com/discovery/filestore/jpeg/Margaret_Interior.jpeg",
		address: "5 Quay Street Circular Quay",
		city: "Sydney",
		state: "NSW",
		zipcode: 2000,
		category: "Japanese",
		rating: 4.5,
		review_count: 100,
	},
];

export default businessList;